export const config = {
  XINFIN_NETWORK_URL: process.env.REACT_APP_XINFIN_NETWORK_URL,
  APOTHEM_NETWORK_URL: process.env.REACT_APP_APOTHEM_NETWORK_URL,
  SUBNET_NETWORK_URL: process.env.REACT_APP_SUBNET_NETWORK_URL,
  PUBLIC_PASS_ADDRESS: process.env.REACT_APP_PUBLIC_PASS_ADDRESS,
  PRIVATE_PASS_ADDRESS: process.env.REACT_APP_PRIVATE_PASS_ADDRESS,
  SUBNET_CHAIN_ID: process.env.REACT_APP_SUBNET_CHAIN_ID,
  APOTHEM_CHAIN_ID: process.env.REACT_APP_APOTHEM_CHAIN_ID,
};
